<?php

declare(strict_types=1);

namespace OCA\CollectiveTodos\Service;

use OCA\Text\Service\DocumentService;
use OCP\Server;
use Psr\Log\LoggerInterface;

/**
 * Reset the Nextcloud Text editor state of a file.
 *
 * The Todos page is regenerated by this app behind the editor's back
 * (NodeWrittenEvent -> putContent). The Text app keeps per-file session and
 * document state (steps, etag, checksum) and would otherwise show stale
 * content in open editors and reject saves with
 * "File changed in the meantime from outside".
 *
 * Resetting the document drops that state, so editors reload the fresh file
 * content. Unsaved manual edits to the Todos page are discarded by design,
 * as the page is auto-generated.
 */
class TextDocumentResetter
{
    private LoggerInterface $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    /**
     * Reset the Text document state for a file, if any exists.
     */
    public function resetForFile(int $fileId): void
    {
        if (!class_exists(DocumentService::class)) {
            return;
        }

        try {
            $documentService = Server::get(DocumentService::class);

            if ($documentService->getDocument($fileId) === null) {
                return;
            }

            $documentService->resetDocument($fileId, true);
        } catch (\Throwable $e) {
            $this->logger->warning('collectives_todos: failed to reset Text document state for file ' . $fileId . ': ' . $e->getMessage(), [
                'exception' => $e,
            ]);
        }
    }
}
